[general]
# Sets the log level for stdout
logging = "DEBUG"

[bot]
# The Bot API token
token = "Your bot token"
# The markup to use [HTML or Markdown]
markup = "HTML"
# Use the language sheets
language_feature = true
