[general]
# Sets the log level for stdout
logging = "DEBUG"
logfile = "Testbot.log"

[bot]
# The Bot API token
#This is the one of the  @deineMuddaBot /KrassTestbot
token = "311199215:AAHzUdqGee2m2NsyjsvQpvOvIQeMboG8CsA"


# Use the language sheets
language_feature = true
#
disable_notification = false
#command to cancel a conversation
cancel_command = "/cancel"

[query]
# Replaces the answered queries
replace_queries = true
